server:
  port: 8085
spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: demo-service-1
          uri: http://localhost:10000
          predicates:
            - Path=/service-1/**
        - id: demo-service-2
          uri: http://localhost:10001
          predicates:
            - Path=/service-2/**